# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy

on:
  create:
      tags: "*"
  # push:
  #   branches: [main, dev]
  # pull_request:
  #   branches: [main, dev]

jobs:
  build:
    runs-on: [self-hosted, pm2]

    steps:
      - name: Run deploy
        run: pm2 deploy production
